name: Trigger Weather DAG

on:
  push:
    branches:
      - main # 當推送到 main 分支時觸發

jobs:
  trigger-dag:
    runs-on: oraclelinux-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trigger Weather DAG
      env:
        AIRFLOW_API_URL: ${{ secret.AIRFLOW_API_URL }}
        AIRFLOW_USERNAME: ${{ secret.AIRFLOW_USERNAME }}
        AIRFLOW_PASSWORD: ${{ secret.AIRFLOW_PASSWORD }}
      run: |
        curl -X POST "$AIRFLOW_API_URL/dags/weather_dag/dagRuns" \
          -H "Content-Type: application/json" \
          -u "$AIRFLOW_USERNAME:$AIRFLOW_PASSWORD" \
          -d "{'conf': {}}"