name: Trigger Weather DAG

on:
  push:
    branches:
      - main # 當推送到 main 分支時觸發

jobs:
  trigger-dag:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trigger Weather DAG
      env:
        AIRFLOW_API_URL: ${{ secrets.AIRFLOW_API_URL }}
        AIRFLOW_USERNAME: ${{ secrets.AIRFLOW_USERNAME }}
        AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
      run: |
        curl -X POST "$AIRFLOW_API_URL/dags/weather_dag/dagRuns" \
          -H "Content-Type: application/json" \
          -u "$AIRFLOW_USERNAME:$AIRFLOW_PASSWORD" \
          -d '{
                "dag_run_id": "string549",
                "logical_date": "2024-08-06T11:34:22Z",
                "execution_date": "2024-08-06T11:34:22Z",
                "conf": { },
                "note": "string"
              }'