name: Trigger Weather DAG

on:
  push:
    branches:
      - main # 當推送到 main 分支時觸發

jobs:
  trigger-dag:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Trigger Weather DAG
      env:
        AIRFLOW_API_URL: ${{ secrets.AIRFLOW_API_URL }}
        AIRFLOW_USERNAME: ${{ secrets.AIRFLOW_USERNAME }}
        AIRFLOW_PASSWORD: ${{ secrets.AIRFLOW_PASSWORD }}
      run: |
        curl -X POST "http://127.0.0.1:8080/api/v1/dags/weather_dag/dagRuns" \
          -H "Content-Type: application/json" \
          -u "admin:c8QB49rm6kUeSAfp" \
          -d '{
                "dag_run_id": "string579",
                "logical_date": "2024-08-04T09:48:22Z",
                "execution_date": "2024-08-04T09:48:22Z",
                "conf": { },
                "note": "string"
              }'